version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eligibility-microservice-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6dwx148qsb19"
s3_prefix = "eligibility-microservice-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
