-- View: carina.training_and_credential

-- DROP VIEW carina.training_and_credential;

CREATE OR REPLACE VIEW carina.training_and_credential
AS WITH CREDENTIAL AS
	(SELECT PS2.PERSONID,
			CR_1.CREDENTIALTYPE,
			CR_1.CREDENTIALNUMBER,
			CR_1.EXPIRATIONDATE
		FROM PROD.CREDENTIAL CR_1
		LEFT JOIN STAGING.PERSONHISTORY PS2 ON PS2.CREDENTIALNUMBER::text = CR_1.CREDENTIALNUMBER::text
		AND PS2.SOURCEKEY::text ~~* 'CRED%'::text
		WHERE CR_1.PRIMARYCREDENTIAL = '1'::smallint ),
	CDWAPROVIDERS AS
	(SELECT T1.PERSONID,
			MAX(T1.LAST_BACKGROUND_CHECK_DATE) AS LAST_BACKGROUND_CHECK_DATE,
			MAX(T1.IE_DATE) AS IE_DATE
		FROM STAGING.PERSONHISTORY T1
		WHERE T1.ISCARINAELIGIBLE = TRUE
			AND T1.SOURCEKEY::text ~~ 'CDWA%'::text
		GROUP BY T1.PERSONID),
	STAGING_PERSONHISTORY AS
	(SELECT *
		FROM
		(SELECT RANK() OVER(PARTITION BY PERSONID ORDER BY RECORDMODIFIEDDATE DESC) AS RK,*
		FROM STAGING.PERSONHISTORY
		WHERE SOURCEKEY::text ~~ 'CDWA%' AND ISCARINAELIGIBLE = TRUE) A
	WHERE RK = 1)
SELECT COALESCE(P.PERSONID,PS.PERSONID) AS STUDENT_ID,
	PS.DSHSID AS DSHS_PROVIDER_ID,
	COALESCE(P.SSN,PS.SSN) AS SSN_LAST_4,
	L.COMPLIANT AS COMPLIANCE_STATUS,
	COALESCE(P.FIRSTNAME::VARCHAR (255),PS.FIRSTNAME::VARCHAR (255)) AS FIRST_NAME,
	COALESCE(P.LASTNAME::VARCHAR (255),PS.LASTNAME::VARCHAR (255)) AS LAST_NAME,
	COALESCE(P.MIDDLENAME::VARCHAR (255),PS.MIDDLENAME::VARCHAR (255)) AS MIDDLE_INITIAL,
	COALESCE(P.DOB,PS.DOB) as DOB,
	COALESCE(P.EMAIL1::VARCHAR (255),PS.EMAIL1::VARCHAR (255)) AS PRIMARY_EMAIL,
	COALESCE(P.MOBILEPHONE,PS.MOBILEPHONE) AS MOBILE_PHONE,
	''::text AS COUNTY,
	COALESCE(P.MAILINGCITY::text,PS.MAILINGCITY) AS MAILING_CITY,
	COALESCE(P.MAILINGSTATE::text,PS.MAILINGSTATE) AS MAILING_STATE,
	COALESCE(P.MAILINGSTREET1,PS.MAILINGSTREET1) AS MAILING_STREET,
	COALESCE(P.MAILINGZIP::text,PS.MAILINGZIP) AS MAILING_POSTAL_CODE,
	P.SFCONTACTID AS SF_CONTACT_ID,
	COALESCE(P.ISCARINAELIGIBLE,PS.ISCARINAELIGIBLE) AS ELIGIBILITY,
	CDWA.IE_DATE AS INTERESTED_AND_ELIGIBLE_DATE,
	COALESCE(P.WORKERCATEGORY::VARCHAR (30),PS.WORKERCATEGORY::VARCHAR (30)) AS TRAINING_CATEGORY,
	COALESCE(P.WORKERCATEGORY::VARCHAR (30),PS.WORKERCATEGORY::VARCHAR (30)) AS ASSIGNEDTRAININGCATEGORY,
	COALESCE(P.EXEMPT,PS.EXEMPT) as EXEMPT,
	CDWA.LAST_BACKGROUND_CHECK_DATE + '2 years'::interval AS BCCU_EXPIRY, 
 	NULL AS CONTRACT_EXPIRY,
	CR.CREDENTIALTYPE,
	CR.CREDENTIALNUMBER,
	CR.EXPIRATIONDATE AS CREDENTIAL_EXPIRY
FROM PROD.PERSON P
FULL JOIN STAGING_PERSONHISTORY PS ON PS.PERSONID::text = P.PERSONID::text
LEFT JOIN STAGING.LEARNER L ON L.PERSONID = COALESCE(PS.PERSONID,P.PERSONID)
LEFT JOIN CREDENTIAL CR ON CR.PERSONID::text = COALESCE(PS.PERSONID::text,P.PERSONID::text) 
LEFT JOIN CDWAPROVIDERS CDWA ON CDWA.PERSONID = COALESCE(PS.PERSONID,P.PERSONID)
WHERE COALESCE(PS.ISCARINAELIGIBLE,P.ISCARINAELIGIBLE) = TRUE
GROUP BY COALESCE(P.PERSONID,PS.PERSONID),
	PS.DSHSID,
	COALESCE(P.SSN,PS.SSN),
	L.COMPLIANT,
	COALESCE(P.FIRSTNAME::VARCHAR (255),PS.FIRSTNAME::VARCHAR (255)),
	COALESCE(P.LASTNAME::VARCHAR (255),PS.LASTNAME::VARCHAR (255)),
	COALESCE(P.MIDDLENAME::VARCHAR (255),PS.MIDDLENAME::VARCHAR (255)),
	COALESCE(P.DOB,PS.DOB),
	COALESCE(P.EMAIL1::VARCHAR (255),PS.EMAIL1::VARCHAR (255)),
	COALESCE(P.MOBILEPHONE,PS.MOBILEPHONE),
	COALESCE(P.MAILINGCITY::text,PS.MAILINGCITY),
	COALESCE(P.MAILINGSTATE::text,PS.MAILINGSTATE),
	COALESCE(P.MAILINGSTREET1,PS.MAILINGSTREET1),
	COALESCE(P.MAILINGZIP::text,PS.MAILINGZIP),
	P.SFCONTACTID,
	COALESCE(P.ISCARINAELIGIBLE,PS.ISCARINAELIGIBLE),
	CDWA.IE_DATE,
	COALESCE(P.WORKERCATEGORY::VARCHAR (30),PS.WORKERCATEGORY::VARCHAR (30)),
	COALESCE(P.WORKERCATEGORY::VARCHAR (30),PS.WORKERCATEGORY::VARCHAR (30)),
	COALESCE(P.EXEMPT,PS.EXEMPT),
	CDWA.LAST_BACKGROUND_CHECK_DATE, 
	CR.CREDENTIALTYPE,
	CR.CREDENTIALNUMBER,
	CR.EXPIRATIONDATE;